# Generated by Django 2.1.2 on 2018-10-14 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='project',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='project',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='TimeLine',
        ),
    ]
